### ISSUE TITLE
why this plugin ignore .prettierrc? how should i use it

### ISSUE THREAD

**Issue by uniquejava** [vuejs/eslint-config-prettier#12]
From my experience,  for any vue project, eslint + prettier is a must and prettier config should be considered with higher priority.

I created a brand new project with `npm init vue@latest`, and I ticked eslint + prettier.

I created a `.prettierrc` file in my vue project root folder

```json
{
  "printWidth": 120,
  "tabWidth": 2,
  "singleQuote": true,
  "bracketSpacing": true,
  "trailingComma": "all",
  "semi": false,
  "useTabs": false,
}
```
now my vscode starts complaining...

<img width="643" alt="image" src="https://user-images.githubusercontent.com/1049271/161911026-dbebd51b-6b45-4e34-a048-80a8901d5fec.png">

If i remove `'@vue/eslint-config-prettier',` from `.eslintrc.js`, everything works normally again.

so my question is why we have this plugin built-in in vue-cli, how should I use it.

@yyx990803 尤大

**Comment by sodatea** [comment]
Can't reproduce. Could you please provide a reproduction repo?

**Comment by uniquejava** [comment]
The typescript file works this time 👍  (I think there must be some changes done in the past 2 months)

However, the `vue` and other files like `cjs` still not work.

reproduction repo:
https://github.com/uniquejava/prettier-not-work

**Comment by uniquejava** [comment]
### Update: the solution is to restart vs code 
I found that after we create `.prettierrc` file, we need to restart vs code, otherwise vs code will still complain the eslint errors. (in vue file this time)

**Comment by TheGreatRefrigerator** [comment]
> ### Update: the solution is to restart vs code
> 
> I found that after we create `.prettierrc` file, we need to restart vs code, otherwise vs code will still complain the eslint errors. (in vue file this time)

Same thing for WebStorm if somebody wonders...

**Comment by itapai** [comment]
It's enough to restart the eslint server in vscode, you don't have to restart the entire vscode.

**Comment by p-kuen** [comment]
As this package only defines some simple eslint config, I believe this is no bug. It's normal that you have to restart the eslint server if you change the configuration. I think this should be closed.
